### model
model_name_or_path: Qwen/Qwen3-VL-2B-Instruct
adapter_name_or_path: medsys/stage1/models/qwen3vl-2B_lora_stage1
image_max_pixels: 65536
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj,linear_fc1,linear_fc2
freeze_vision_tower: true
freeze_multi_modal_projector: false
freeze_language_model: false

### dataset
dataset: pmc_vqa2_train,vqa_rad_train
template: qwen3_vl_nothink
cutoff_len: 1024
val_size: 0.2
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: medsys/stage2/models/qwen3vl-2B_lora_stage2_pmc_vqa_rad
logging_steps: 10
save_steps: 500
save_total_limit: 3
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
use_swanlab: true
swanlab_project: medsys
swanlab_run_name: qwen3vl-2B_lora_stage2_pmc_vqa_rad

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 250
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false